apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda:10.1-base
      resources:
        limits:
          nvidia.com/gpu: 1
      command: ["sh", "-c", "nvidia-smi; sleep 36000"]
  nodeSelector:
    accelerator: nvidia-tesla-m6 # or nvidia-tesla-k80 etc.

